export const string = {
    HOME: "Home",
    ABOUT: "About",
    CONTACT: "Contact",
    COMMENT: "Comment",
    LOGIN: "Login",
    REGISTER: "Register",
    DASHBOARD: "Dashboard",
    TEAM: "Team",
    FORGOT_PASSWORD: "Forgot Password?",
    FORGOT_PASSWORD_SUBMIT: "Submit",
    FORGOT_PASSWORD_SUCCESS: "Password reset successfully.",
    FORGOT_PASSWORD_ERROR: "Error resetting password.",
    CHANGE_PASSWORD: "Change Password",
    CHANGE_PASSWORD_SUCCESS: "Password changed successfully.",
    CHANGE_PASSWORD_ERROR: "Error changing password.",
    RESET_PASSWORD: "Reset Password",
    RESET_PASSWORD_SUCCESS: "Password reset successfully.",
    RESET_PASSWORD_ERROR: "Error resetting password.",
    EVENT: "Events",
    DOWNLOAD_RESUME: "Download Resume",
    DONWLOAD: "Download",
    CURRENT_LOCATION: "Current Location",
    LIKE: "Like"
}